apiVersion: v1
kind: Pod
metadata:
  name: audit-pod
  labels:
    app: audit-pod
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: localhost/profiles/audit.json
spec:
  containers:
  - name: test-container
    image: busybox
    args:
    - "sleep"
    - "1d"
    securityContext:
      allowPrivilegeEscalation: false
  nodeSelector:
    pod: seccomp
